/**
 * Mock Data - Development ve test için
 * Backend yoksa bu mock data kullanılır
 */

// Mock loyalty data - 20 adet
export const mockLoyaltyData = [
  {
    cafeId: 1,
    cafeName: 'Starbucks',
    orderCount: 7,
    freeProductAt: 10,
    points: 70,
    city: 'İstanbul',
    district: 'Kadıköy',
    neighborhood: 'Moda',
    foodTypes: ['Kahve', 'Pasta'],
    hasCampaign: true,
    lastOrderDate: '2024-01-15',
  },
  {
    cafeId: 2,
    cafeName: 'Kahve Dünyası',
    orderCount: 15,
    freeProductAt: 10,
    points: 150,
    city: 'İstanbul',
    district: 'Beşiktaş',
    neighborhood: 'Bebek',
    foodTypes: ['Kahve', 'Çay'],
    hasCampaign: false,
    lastOrderDate: '2024-01-20',
  },
  {
    cafeId: 3,
    cafeName: 'Gloria Jeans',
    orderCount: 3,
    freeProductAt: 10,
    points: 30,
    city: 'İstanbul',
    district: 'Şişli',
    neighborhood: 'Nişantaşı',
    foodTypes: ['Kahve', 'Sandviç'],
    hasCampaign: true,
    lastOrderDate: '2024-01-10',
  },
  {
    cafeId: 4,
    cafeName: 'Coffeeshop Company',
    orderCount: 12,
    freeProductAt: 10,
    points: 120,
    city: 'İstanbul',
    district: 'Beyoğlu',
    neighborhood: 'Taksim',
    foodTypes: ['Kahve', 'Pasta', 'Salata'],
    hasCampaign: true,
    lastOrderDate: '2024-01-18',
  },
  {
    cafeId: 5,
    cafeName: 'Mado',
    orderCount: 5,
    freeProductAt: 10,
    points: 50,
    city: 'İstanbul',
    district: 'Üsküdar',
    neighborhood: 'Ortaköy',
    foodTypes: ['Dondurma', 'Pasta'],
    hasCampaign: false,
    lastOrderDate: '2024-01-12',
  },
  {
    cafeId: 6,
    cafeName: 'Caffe Nero',
    orderCount: 9,
    freeProductAt: 10,
    points: 90,
    city: 'Ankara',
    district: 'Çankaya',
    neighborhood: 'Kızılay',
    foodTypes: ['Kahve', 'Sandviç'],
    hasCampaign: true,
    lastOrderDate: '2024-01-16',
  },
  {
    cafeId: 7,
    cafeName: 'Kahve Diyarı',
    orderCount: 18,
    freeProductAt: 10,
    points: 180,
    city: 'İstanbul',
    district: 'Kadıköy',
    neighborhood: 'Moda',
    foodTypes: ['Kahve', 'Çay', 'Pasta'],
    hasCampaign: true,
    lastOrderDate: '2024-01-22',
  },
  {
    cafeId: 8,
    cafeName: 'Burger King',
    orderCount: 4,
    freeProductAt: 10,
    points: 40,
    city: 'İstanbul',
    district: 'Beşiktaş',
    neighborhood: 'Bebek',
    foodTypes: ['Burger', 'Patates'],
    hasCampaign: false,
    lastOrderDate: '2024-01-08',
  },
  {
    cafeId: 9,
    cafeName: 'Pizza Hut',
    orderCount: 11,
    freeProductAt: 10,
    points: 110,
    city: 'İzmir',
    district: 'Konak',
    neighborhood: 'Alsancak',
    foodTypes: ['Pizza', 'Salata'],
    hasCampaign: true,
    lastOrderDate: '2024-01-19',
  },
  {
    cafeId: 10,
    cafeName: 'Domino\'s Pizza',
    orderCount: 6,
    freeProductAt: 10,
    points: 60,
    city: 'İstanbul',
    district: 'Şişli',
    neighborhood: 'Nişantaşı',
    foodTypes: ['Pizza'],
    hasCampaign: true,
    lastOrderDate: '2024-01-14',
  },
  {
    cafeId: 11,
    cafeName: 'Simit Sarayı',
    orderCount: 20,
    freeProductAt: 10,
    points: 200,
    city: 'İstanbul',
    district: 'Beyoğlu',
    neighborhood: 'Taksim',
    foodTypes: ['Simit', 'Çay', 'Peynir'],
    hasCampaign: false,
    lastOrderDate: '2024-01-23',
  },
  {
    cafeId: 12,
    cafeName: 'Baydoner',
    orderCount: 8,
    freeProductAt: 10,
    points: 80,
    city: 'Ankara',
    district: 'Çankaya',
    neighborhood: 'Kızılay',
    foodTypes: ['Döner', 'Lahmacun'],
    hasCampaign: true,
    lastOrderDate: '2024-01-17',
  },
  {
    cafeId: 13,
    cafeName: 'KFC',
    orderCount: 13,
    freeProductAt: 10,
    points: 130,
    city: 'İstanbul',
    district: 'Üsküdar',
    neighborhood: 'Ortaköy',
    foodTypes: ['Tavuk', 'Patates'],
    hasCampaign: true,
    lastOrderDate: '2024-01-21',
  },
  {
    cafeId: 14,
    cafeName: 'McDonald\'s',
    orderCount: 16,
    freeProductAt: 10,
    points: 160,
    city: 'İzmir',
    district: 'Konak',
    neighborhood: 'Alsancak',
    foodTypes: ['Burger', 'Patates'],
    hasCampaign: false,
    lastOrderDate: '2024-01-24',
  },
  {
    cafeId: 15,
    cafeName: 'Popeyes',
    orderCount: 2,
    freeProductAt: 10,
    points: 20,
    city: 'İstanbul',
    district: 'Kadıköy',
    neighborhood: 'Moda',
    foodTypes: ['Tavuk', 'Patates'],
    hasCampaign: true,
    lastOrderDate: '2024-01-05',
  },
  {
    cafeId: 16,
    cafeName: 'Nusret',
    orderCount: 19,
    freeProductAt: 10,
    points: 190,
    city: 'İstanbul',
    district: 'Beşiktaş',
    neighborhood: 'Bebek',
    foodTypes: ['Et', 'Salata'],
    hasCampaign: false,
    lastOrderDate: '2024-01-25',
  },
  {
    cafeId: 17,
    cafeName: 'Zomato',
    orderCount: 10,
    freeProductAt: 10,
    points: 100,
    city: 'Ankara',
    district: 'Çankaya',
    neighborhood: 'Kızılay',
    foodTypes: ['Çeşitli'],
    hasCampaign: true,
    lastOrderDate: '2024-01-13',
  },
  {
    cafeId: 18,
    cafeName: 'Yemeksepeti',
    orderCount: 14,
    freeProductAt: 10,
    points: 140,
    city: 'İzmir',
    district: 'Konak',
    neighborhood: 'Alsancak',
    foodTypes: ['Çeşitli'],
    hasCampaign: true,
    lastOrderDate: '2024-01-11',
  },
  {
    cafeId: 19,
    cafeName: 'Getir',
    orderCount: 17,
    freeProductAt: 10,
    points: 170,
    city: 'İstanbul',
    district: 'Şişli',
    neighborhood: 'Nişantaşı',
    foodTypes: ['Çeşitli'],
    hasCampaign: false,
    lastOrderDate: '2024-01-09',
  },
  {
    cafeId: 20,
    cafeName: 'Migros',
    orderCount: 1,
    freeProductAt: 10,
    points: 10,
    city: 'İstanbul',
    district: 'Beyoğlu',
    neighborhood: 'Taksim',
    foodTypes: ['Market'],
    hasCampaign: true,
    lastOrderDate: '2024-01-03',
  },
];

// Mock cafe search results - 20 adet
export const mockCafeSearch = (query) => {
  // mockNearbyCafes ile aynı veriyi kullan
  const allCafes = mockNearbyCafes(41.0082, 28.9784);

  if (!query || !query.trim()) return allCafes;

  const lowerQuery = query.toLowerCase();
  return allCafes.filter(
    (cafe) =>
      (cafe.name || '').toLowerCase().includes(lowerQuery) ||
      (cafe.address || '').toLowerCase().includes(lowerQuery)
  );
};

// Mock nearby cafes - 20 adet
export const mockNearbyCafes = (latitude, longitude) => {
  return [
    {
      id: 1,
      name: 'Starbucks',
      address: 'Kadıköy, İstanbul',
      latitude: 40.9882,
      longitude: 29.0244,
      distance: 0.5,
      restaurantType: 'Kafe',
      hasCampaign: true,
    },
    {
      id: 2,
      name: 'Kahve Dünyası',
      address: 'Beşiktaş, İstanbul',
      latitude: 41.0422,
      longitude: 29.0084,
      distance: 1.2,
      restaurantType: 'Kafe',
      hasCampaign: false,
    },
    {
      id: 3,
      name: 'Gloria Jeans',
      address: 'Şişli, İstanbul',
      latitude: 41.0602,
      longitude: 28.9874,
      distance: 2.5,
      restaurantType: 'Kafe',
      hasCampaign: true,
    },
    {
      id: 4,
      name: 'Coffeeshop Company',
      address: 'Beyoğlu, İstanbul',
      latitude: 41.0369,
      longitude: 28.9850,
      distance: 3.1,
      restaurantType: 'Kafe',
      hasCampaign: true,
    },
    {
      id: 5,
      name: 'Mado',
      address: 'Üsküdar, İstanbul',
      latitude: 41.0214,
      longitude: 29.0124,
      distance: 0.8,
      restaurantType: 'Pastane',
      hasCampaign: false,
    },
    {
      id: 6,
      name: 'Caffe Nero',
      address: 'Çankaya, Ankara',
      latitude: 39.9208,
      longitude: 32.8541,
      distance: 5.2,
      restaurantType: 'Kafe',
      hasCampaign: true,
    },
    {
      id: 7,
      name: 'Kahve Diyarı',
      address: 'Kadıköy, İstanbul',
      latitude: 40.9900,
      longitude: 29.0200,
      distance: 0.6,
      restaurantType: 'Kafe',
      hasCampaign: true,
    },
    {
      id: 8,
      name: 'Burger King',
      address: 'Beşiktaş, İstanbul',
      latitude: 41.0400,
      longitude: 29.0100,
      distance: 1.0,
      restaurantType: 'Restoran',
      hasCampaign: false,
    },
    {
      id: 9,
      name: 'Pizza Hut',
      address: 'Alsancak, İzmir',
      latitude: 38.4237,
      longitude: 27.1428,
      distance: 8.5,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
    {
      id: 10,
      name: 'Domino\'s Pizza',
      address: 'Şişli, İstanbul',
      latitude: 41.0580,
      longitude: 28.9850,
      distance: 2.3,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
    {
      id: 11,
      name: 'Simit Sarayı',
      address: 'Beyoğlu, İstanbul',
      latitude: 41.0350,
      longitude: 28.9800,
      distance: 3.0,
      restaurantType: 'Pastane',
      hasCampaign: false,
    },
    {
      id: 12,
      name: 'Baydoner',
      address: 'Kızılay, Ankara',
      latitude: 39.9180,
      longitude: 32.8560,
      distance: 5.0,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
    {
      id: 13,
      name: 'KFC',
      address: 'Ortaköy, İstanbul',
      latitude: 41.0470,
      longitude: 29.0240,
      distance: 1.5,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
    {
      id: 14,
      name: 'McDonald\'s',
      address: 'Alsancak, İzmir',
      latitude: 38.4250,
      longitude: 27.1400,
      distance: 8.3,
      restaurantType: 'Restoran',
      hasCampaign: false,
    },
    {
      id: 15,
      name: 'Popeyes',
      address: 'Moda, İstanbul',
      latitude: 40.9850,
      longitude: 29.0250,
      distance: 0.4,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
    {
      id: 16,
      name: 'Nusret',
      address: 'Bebek, İstanbul',
      latitude: 41.0780,
      longitude: 29.0430,
      distance: 2.8,
      restaurantType: 'Restoran',
      hasCampaign: false,
    },
    {
      id: 17,
      name: 'Zomato',
      address: 'Kızılay, Ankara',
      latitude: 39.9200,
      longitude: 32.8580,
      distance: 5.1,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
    {
      id: 18,
      name: 'Yemeksepeti',
      address: 'Alsancak, İzmir',
      latitude: 38.4240,
      longitude: 27.1410,
      distance: 8.4,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
    {
      id: 19,
      name: 'Getir',
      address: 'Nişantaşı, İstanbul',
      latitude: 41.0480,
      longitude: 28.9900,
      distance: 2.0,
      restaurantType: 'Restoran',
      hasCampaign: false,
    },
    {
      id: 20,
      name: 'Migros',
      address: 'Taksim, İstanbul',
      latitude: 41.0370,
      longitude: 28.9850,
      distance: 3.2,
      restaurantType: 'Restoran',
      hasCampaign: true,
    },
  ];
};

// Mock login response
export const mockLoginResponse = (email, password) => {
  // Basit mock - gerçek uygulamada backend'den gelir
  return {
    token: 'mock_jwt_token_' + Date.now(),
    user: {
      id: 1,
      email: email,
      name: 'Test User',
    },
  };
};

// Mock signup response
export const mockSignupResponse = (email, password) => {
  return {
    token: 'mock_jwt_token_' + Date.now(),
    user: {
      id: 2,
      email: email,
      name: 'New User',
    },
  };
};

